## Merge two nutritons data set

In [150]:
import pandas as pd

In [151]:
sri_lankan_nutrition_foods_1 = pd.read_csv('../../data/RecommandationDatasets/Sri_Lankan_Nutritions.csv') 
sri_lankan_nutrition_foods_2 = pd.read_csv('../../data/RecommandationDatasets/SrilankanCommonFoods.csv')
sri_lankan_nutrition_foods_3 = pd.read_csv('../../data/RecommandationDatasets/sri_lankan_food_types.csv')
# Load the food_items dataset

In [152]:
sri_lankan_nutrition_foods_1.head()

,FCT source,drfoodlistcode,drfoodlistdesc,Recipe/Single food item,Energy (kcal),Protein (g),Total fats (g),Total carbohydrates (g),Fiber (g),Starch (g),...,Vitamin B5 (mg),Phosphorus (mg),Potassium (mg),Sodium (mg),Selenium (mcg),Retinol (mcg),Saturated fatty acids (g),Mono-unsaturated fatty acids (g),Poly-unsaturated fatty acids (g),Free sugars (g)
0,"ASEAN FCT #AAP1 Beer, pale pilsen",10010001,BEER,S,43.0,0.0,0.46,3.55,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wayamba 2022 SPIRITS,10010002,"LIQUOR, ARAK",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wayamba 2022 SPIRITS,10010003,"LIQUOR, KASIPPU",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wayamba 2022 SPIRITS,10010004,"LIQUOR, TODDY, COCONUT",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Wayamba 2022 SPIRITS,10010006,"LIQUOR, TODDY, KITUL",S,222.0,0.0,0.00,0.00,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
sri_lankan_nutrition_foods_1.drop(columns=["FCT source","drfoodlistcode"], inplace=True)

In [154]:

# Clean all column names
sri_lankan_nutrition_foods_1.columns = sri_lankan_nutrition_foods_1.columns.str.strip()                     # Removes leading/trailing spaces and \n
sri_lankan_nutrition_foods_1.columns = sri_lankan_nutrition_foods_1.columns.str.replace('\n', '', regex=True)  # Removes newlines
sri_lankan_nutrition_foods_1.columns = sri_lankan_nutrition_foods_1.columns.str.replace(' ', '_')           # Optional: Replace spaces with underscores

sri_lankan_nutrition_foods_1.rename(columns={
    'drfoodlistdesc': 'Food',
    'Energy_(kcal)':'Calories_(kcal)',
    'Total_fats_(g)': 'Fats_(g)',
    'Total_carbohydrates_(g)': 'Carbohydrates_(g)',
}, inplace=True)
sri_lankan_nutrition_foods_1.head()

,Food,Recipe/Single_food_item,Calories_(kcal),Protein_(g),Fats_(g),Carbohydrates_(g),Fiber_(g),Starch_(g),Cholesterol_(mg),Calcium_(mg),...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,BEER,S,43.0,0.0,0.46,3.55,0,0.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"LIQUOR, ARAK",S,222.0,0.0,0.00,0.00,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"LIQUOR, KASIPPU",S,222.0,0.0,0.00,0.00,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"LIQUOR, TODDY, COCONUT",S,222.0,0.0,0.00,0.00,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"LIQUOR, TODDY, KITUL",S,222.0,0.0,0.00,0.00,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:

# Clean all column names
sri_lankan_nutrition_foods_2.columns = sri_lankan_nutrition_foods_2.columns.str.strip()                     # Removes leading/trailing spaces and \n
sri_lankan_nutrition_foods_2.columns = sri_lankan_nutrition_foods_2.columns.str.replace('\n', '', regex=True)  # Removes newlines
sri_lankan_nutrition_foods_2.columns = sri_lankan_nutrition_foods_2.columns.str.replace(' ', '_')           # Optional: Replace spaces with underscores

sri_lankan_nutrition_foods_2.rename(columns={
    'drfoodlistdesc': 'Food',
    'Calories (kcal)':'Calories_(kcal)',
    'Fat (g)': 'Fats_(g)',
    'Carbohydrate (g)': 'Carbohydrates_(g)',
}, inplace=True)
sri_lankan_nutrition_foods_2.head()

          Food Quantity Calories_(kcal) Carbohydrate_(g) Protein_(g) Fat_(g)
0   White Rice      80g        110 kcal              24g          2g      0g
1   Brown Rice      80g         90 kcal              19g          2g      1g
2     Red Rice      80g        112 kcal              23g        2.4g    0.8g
3  White Bread     100g        270 kcal              50g          9g      3g
4        Pasta     250g        393 kcal              79g         14g    1.7g

In [156]:
sri_lankan_nutrition_foods_3.head()

,Food ID,Food Name,Category,Region,Price (LKR),Calories,Vegetarian
0,1,Sri Lankan Salad,Breakfast,Anuradhapura,673.64,848,No
1,2,String Hoppers,Lunch,Jaffna,831.09,414,No
2,3,Sri Lankan Coffee,Lunch,Kurunegala,326.39,463,No
3,4,Seeni Sambol,Beverage,Colombo,781.57,810,Yes
4,5,Kiri Hodhi,Lunch,Batticaloa,151.76,245,No

In [157]:
sri_lankan_nutrition_foods_3.drop(columns=["Food ID","Region","Price (LKR)"], inplace=True)

In [158]:
sri_lankan_nutrition_foods_3.columns = sri_lankan_nutrition_foods_3.columns.str.strip()                     # Removes leading/trailing spaces and \n
sri_lankan_nutrition_foods_3.columns = sri_lankan_nutrition_foods_3.columns.str.replace('\n', '', regex=True)  # Removes newlines
sri_lankan_nutrition_foods_3.columns = sri_lankan_nutrition_foods_3.columns.str.replace(' ', '_')           # Optional: Replace spaces with underscores

sri_lankan_nutrition_foods_3.rename(columns={
    'Food_Name': 'Food',
    'Calories': 'Calories_(kcal)',
}, inplace=True)
sri_lankan_nutrition_foods_3.head()

                Food   Category  Calories_(kcal) Vegetarian
0   Sri Lankan Salad  Breakfast              848         No
1     String Hoppers      Lunch              414         No
2  Sri Lankan Coffee      Lunch              463         No
3       Seeni Sambol   Beverage              810        Yes
4         Kiri Hodhi      Lunch              245         No

In [160]:
sri_lankan_nutrition_foods_2.head()

          Food Quantity Calories_(kcal) Carbohydrate_(g) Protein_(g) Fat_(g)
0   White Rice      80g        110 kcal              24g          2g      0g
1   Brown Rice      80g         90 kcal              19g          2g      1g
2     Red Rice      80g        112 kcal              23g        2.4g    0.8g
3  White Bread     100g        270 kcal              50g          9g      3g
4        Pasta     250g        393 kcal              79g         14g    1.7g

### Merge Datasets

In [161]:
# Ensure 'Food' column is clean and consistent in all DataFrames
for df in [sri_lankan_nutrition_foods_1, sri_lankan_nutrition_foods_2, sri_lankan_nutrition_foods_3]:
    df['Food'] = df['Food'].astype(str).str.strip().str.upper()

# Merge all three DataFrames on 'Food'
merged = pd.merge(
    sri_lankan_nutrition_foods_2, 
    sri_lankan_nutrition_foods_3, 
    on='Food', 
    how='outer', 
)
merged_all = pd.merge(
    merged, 
    sri_lankan_nutrition_foods_1, 
    on='Food', 
    how='outer', 
    suffixes=('', '_nutritions')
)

In [162]:
merged_all.head()

,Food,Quantity,Calories_(kcal)_x,Carbohydrate_(g),Protein_(g),Fat_(g),Category,Calories_(kcal)_y,Vegetarian,Recipe/Single_food_item,...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,ADA,80g,280 kcal,61g,5g,2g,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"AGATHI FLOWERS, TEMPERED",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,...,0.802873,78.340317,809.414307,20.901785,30.841963,NaN,NaN,NaN,NaN,2.595276
2,AGGALA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALMONDS,30g,180 kcal,6g,6g,15g,NaN,NaN,NaN,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALUWA,100g,400 kcal,85g,3g,8g,NaN,NaN,NaN,S,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [163]:
# Combine main nutrition columns
for col in ['Calories_(kcal)', 'Carbohydrate_(g)', 'Protein_(g)', 'Fat_(g)']:
    x_col = f"{col}_x"
    y_col = f"{col}_y"
    if x_col in merged_all.columns and y_col in merged_all.columns:
        merged_all[col] = merged_all[x_col].combine_first(merged_all[y_col])
        merged_all = merged_all.drop(columns=[x_col, y_col])

In [164]:
merged_all.head()

,Food,Quantity,Carbohydrate_(g),Protein_(g),Fat_(g),Category,Vegetarian,Recipe/Single_food_item,Calories_(kcal),Protein_(g)_nutritions,...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,ADA,80g,61g,5g,2g,NaN,NaN,NaN,280 kcal,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"AGATHI FLOWERS, TEMPERED",NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,9.288287,...,0.802873,78.340317,809.414307,20.901785,30.841963,NaN,NaN,NaN,NaN,2.595276
2,AGGALA,NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,3.700000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALMONDS,30g,6g,6g,15g,NaN,NaN,S,180 kcal,18.400000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALUWA,100g,85g,3g,8g,NaN,NaN,S,400 kcal,3.300000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [165]:
for col, unit in [
    ('Carbohydrate_(g)', 'g'),
    ('Quantity','g'),
    ('Protein_(g)', 'g'),
    ('Fat_(g)', 'g'),
    ('Calories_(kcal)', 'kcal')
]:
    if col in merged_all.columns:
        merged_all[col] = (
            merged_all[col]
            .astype(str)
            .str.replace(unit, '', regex=False)
            .str.strip()
        )
        merged_all[col] = pd.to_numeric(merged_all[col], errors='coerce')

In [166]:
merged_all.head()

,Food,Quantity,Carbohydrate_(g),Protein_(g),Fat_(g),Category,Vegetarian,Recipe/Single_food_item,Calories_(kcal),Protein_(g)_nutritions,...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,ADA,80.0,61.0,5.0,2.0,NaN,NaN,NaN,280.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"AGATHI FLOWERS, TEMPERED",NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,9.288287,...,0.802873,78.340317,809.414307,20.901785,30.841963,NaN,NaN,NaN,NaN,2.595276
2,AGGALA,NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,3.700000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALMONDS,30.0,6.0,6.0,15.0,NaN,NaN,S,180.0,18.400000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALUWA,100.0,85.0,3.0,8.0,NaN,NaN,S,400.0,3.300000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [167]:
if 'Recipe/Single_food_item' in merged_all.columns:
    merged_all['Recipe/Single_food_item'] = merged_all['Recipe/Single_food_item'].fillna('S')

In [168]:
merged_all.head()

,Food,Quantity,Carbohydrate_(g),Protein_(g),Fat_(g),Category,Vegetarian,Recipe/Single_food_item,Calories_(kcal),Protein_(g)_nutritions,...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,ADA,80.0,61.0,5.0,2.0,NaN,NaN,S,280.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"AGATHI FLOWERS, TEMPERED",NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,9.288287,...,0.802873,78.340317,809.414307,20.901785,30.841963,NaN,NaN,NaN,NaN,2.595276
2,AGGALA,NaN,NaN,NaN,NaN,NaN,NaN,R,NaN,3.700000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ALMONDS,30.0,6.0,6.0,15.0,NaN,NaN,S,180.0,18.400000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALUWA,100.0,85.0,3.0,8.0,NaN,NaN,S,400.0,3.300000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [169]:
merged_all.to_csv("../../data/RecommandationDatasets/NutritionsDatasets/updatedSLNutritions.csv", index=False)

In [170]:
from sklearn.impute import KNNImputer
import numpy as np

# Copy of the original dataframe
df_cleaned = merged_all.copy()

# Step 1: Handle object-based columns logically where possible
# Fill 'Category' and 'Vegetarian' based on mode within 'Recipe/Single_food_item'
for col in ['Category', 'Vegetarian']:
    df_cleaned[col] = df_cleaned.groupby('Recipe/Single_food_item')[col].transform(
        lambda x: x.fillna(x.mode().iloc[0]) if not x.mode().empty else x
    )

# Step 2: Convert non-numeric columns to be excluded from KNN imputation
non_numeric_cols = df_cleaned.select_dtypes(include='object').columns.tolist()
numeric_df = df_cleaned.drop(columns=non_numeric_cols)

# Some columns like 'Fiber_(g)' have object types — attempt conversion
for col in numeric_df.columns:
    numeric_df[col] = pd.to_numeric(numeric_df[col], errors='coerce')

# Step 3: Apply KNN Imputation for numeric columns
imputer = KNNImputer(n_neighbors=5)
numeric_imputed = imputer.fit_transform(numeric_df)

# Step 4: Convert back to DataFrame and combine with non-numeric columns
df_imputed_numeric = pd.DataFrame(numeric_imputed, columns=numeric_df.columns)
df_final = pd.concat([df_cleaned[non_numeric_cols].reset_index(drop=True), df_imputed_numeric], axis=1)

# Preview a few rows where NaNs previously existed
rows_with_prev_nans = df[df.isna().any(axis=1)].index[:5]
df_final.loc[rows_with_prev_nans]

Empty DataFrame
Columns: [Food, Category, Vegetarian, Recipe/Single_food_item, Fiber_(g), Quantity, Carbohydrate_(g), Protein_(g), Fat_(g), Calories_(kcal), Protein_(g)_nutritions, Fats_(g), Carbohydrates_(g), Starch_(g), Cholesterol_(mg), Calcium_(mg), Magnesium_(mg), Iron_(mg), Zinc_(mg), Thiamin_(mg), Riboflavin_(mg), Niacin_(mg), Vitamin_B6_(mg), Vitamin_B12_(mcg), Folate,_ug, Vitamin_C_(mg), Retinol_Activity_Equivalents_(ug), Vitamin_E_(ug), total_n-6_fas_(%_of_energy), total_n-3_fas_(%_of_energy), Vitamin_B5_(mg), Phosphorus_(mg), Potassium_(mg), Sodium_(mg), Selenium_(mcg), Retinol_(mcg), Saturated_fatty_acids_(g), Mono-unsaturated_fatty_acids_(g), Poly-unsaturated_fatty_acids_(g), Free_sugars_(g)]
Index: []

[0 rows x 40 columns]

In [172]:
df_final.head()

,Food,Category,Vegetarian,Recipe/Single_food_item,Fiber_(g),Quantity,Carbohydrate_(g),Protein_(g),Fat_(g),Calories_(kcal),...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,ADA,Breakfast,Yes,S,NaN,80.0,61.00,5.00,2.00,280.0,...,0.360973,68.693968,200.704441,35.511988,6.500015,46.333333,1176.444664,1161.202582,388.712078,0.973530
1,"AGATHI FLOWERS, TEMPERED",Dessert,Yes,R,10.40014553,86.0,36.40,5.70,13.26,366.2,...,0.802873,78.340317,809.414307,20.901785,30.841963,187.600000,120.533872,80.577045,209.227992,2.595276
2,AGGALA,Dessert,Yes,R,0,86.0,60.84,4.22,5.10,333.4,...,0.102150,16.912391,49.417958,19.624399,6.694397,7.800000,0.910000,0.951600,0.376000,10.237877
3,ALMONDS,Breakfast,Yes,S,13.1,30.0,6.00,6.00,15.00,180.0,...,1.111365,308.947402,919.948504,29.137727,15.441434,3.200000,1805.790660,6151.048678,2334.153246,2.196241
4,ALUWA,Breakfast,Yes,S,1.2,100.0,85.00,3.00,8.00,400.0,...,0.102150,16.912391,49.417958,19.624399,6.694397,7.800000,88.109880,78.689810,104.957570,10.237229

In [173]:
df_final.drop(columns=["Vegetarian"], inplace=True)

In [177]:
df_final.to_csv("../../data/RecommandationDatasets/NutritionsDatasets/SLNutritionsFood.csv", index=False)

In [178]:
df_final.head()

,Food,Category,Recipe/Single_food_item,Fiber_(g),Quantity,Carbohydrate_(g),Protein_(g),Fat_(g),Calories_(kcal),Protein_(g)_nutritions,...,Vitamin_B5_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Selenium_(mcg),Retinol_(mcg),Saturated_fatty_acids_(g),Mono-unsaturated_fatty_acids_(g),Poly-unsaturated_fatty_acids_(g),Free_sugars_(g)
0,ADA,Breakfast,S,NaN,80.0,61.00,5.00,2.00,280.0,5.384331,...,0.360973,68.693968,200.704441,35.511988,6.500015,46.333333,1176.444664,1161.202582,388.712078,0.973530
1,"AGATHI FLOWERS, TEMPERED",Dessert,R,10.40014553,86.0,36.40,5.70,13.26,366.2,9.288287,...,0.802873,78.340317,809.414307,20.901785,30.841963,187.600000,120.533872,80.577045,209.227992,2.595276
2,AGGALA,Dessert,R,0,86.0,60.84,4.22,5.10,333.4,3.700000,...,0.102150,16.912391,49.417958,19.624399,6.694397,7.800000,0.910000,0.951600,0.376000,10.237877
3,ALMONDS,Breakfast,S,13.1,30.0,6.00,6.00,15.00,180.0,18.400000,...,1.111365,308.947402,919.948504,29.137727,15.441434,3.200000,1805.790660,6151.048678,2334.153246,2.196241
4,ALUWA,Breakfast,S,1.2,100.0,85.00,3.00,8.00,400.0,3.300000,...,0.102150,16.912391,49.417958,19.624399,6.694397,7.800000,88.109880,78.689810,104.957570,10.237229